package ac.su.suport.livescore.constant;

public enum DepartmentEnum {
    THEOLOGY,
    NURSING,
    PHARMACY,
    EARLY_CHILDHOOD_EDUCATION,
    MUSIC,
    ART_AND_DESIGN,
    PHYSICAL_EDUCATION,
    SOCIAL_WELFARE,
    COUNSELING_PSYCHOLOGY,
    ENGLISH_LITERATURE,
    AVIATION_TOURISM_FOREIGN_LANGUAGES,
    GLOBAL_KOREAN_STUDIES,
    BUSINESS_ADMINISTRATION,
    COMPUTER_SCIENCE,
    AI_CONVERGENCE,
    FOOD_NUTRITION,
    HEALTH_MANAGEMENT,
    ENVIRONMENTAL_DESIGN_HORTICULTURE,
    ANIMAL_RESOURCE_SCIENCE,
    CHEMISTRY_LIFE_SCIENCE,
    BIO_CONVERGENCE_ENGINEERING,
    ARCHITECTURE,
    PHYSICAL_THERAPY,
    DATA_CLOUD_ENGINEERING,
    FACULTY_TEAM
}