name: Deploy to Amazon EC2 through Bastion

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-northeast-2
  BASTION_HOST: ${{ secrets.BASTION_HOST }}
  BASTION_USER: ${{ secrets.BASTION_USER }}
  WEB01_HOST: ${{ secrets.WEB01_HOST }}
  WEB_USER: ${{ secrets.WEB_USER }}

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy to EC2 through Bastion
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Copy JAR to Bastion
        uses: appleboy/scp-action@v0.1.3
        with:
          host: bastion
          username: ${{ secrets.BASTION_USER }}
          key: ${{ secrets.BASTION_KEY }}
          source: "build/libs/*.jar"
          target: "/home/${{ secrets.BASTION_USER }}/livescore/"

      - name: Deploy on Web01 through Bastion
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: bastion
          username: ${{ secrets.BASTION_USER }}
          key: ${{ secrets.BASTION_KEY }}
          script: |
            ssh -o StrictHostKeyChecking=no web01 << 'EOF'
              if ! rpm -qa | grep -qw java-17-amazon-corretto-devel; then
                sudo rpm --import https://yum.corretto.aws/corretto.key
                sudo curl -L -o /etc/yum.repos.d/corretto.repo https://yum.corretto.aws/corretto.repo
                sudo yum install -y java-17-amazon-corretto-devel
              fi
              pkill -f 'java -jar' || true
              nohup java -jar /home/${{ secrets.BASTION_USER }}/livescore/*.jar > /home/${{ secrets.WEB_USER }}/your-app/app.log 2>&1 &
            EOF

      - name: Verify Deployment
        run: curl -I http://${{ secrets.WEB01_HOST }}
        # run: curl -I http://your-domain.com 도메인 파면 해당 라인 사용
